import React, { useState } from 'react';
import { Card, Field, PageHead, Status } from '../components/UI';
import { useBorrowerStore } from '../state/store';

export function AccountPage(){
  const {state,updateProfile,setLocale}=useBorrowerStore(); const [draft,setDraft]=useState(state.profile);const[message,setMessage]=useState('');
  const save=(e:React.FormEvent)=>{e.preventDefault();if(!draft.name.trim()||!draft.email.includes('@')){setMessage('Name and a valid email are required.');return;}updateProfile(draft);setMessage('Profile settings saved.');};
  return <div className="route-stage narrow-stage"><PageHead eyebrow="Borrower / Account" title="Account" subtitle="Personal profile, language, notification preferences and session context."/><form className="form-card" onSubmit={save}><div className="form-grid two"><Field label="Name"><input value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Job title"><input value={draft.jobTitle} onChange={(e)=>setDraft({...draft,jobTitle:e.target.value})}/></Field><Field label="Email"><input type="email" value={draft.email} onChange={(e)=>setDraft({...draft,email:e.target.value})}/></Field><Field label="Phone"><input type="tel" value={draft.phone} onChange={(e)=>setDraft({...draft,phone:e.target.value})}/></Field></div><div className="setting-row"><span><strong>Preferred language</strong><small>Applies immediately to shared Borrower navigation.</small></span><div className="language-switch large"><button type="button" className={state.locale==='en'?'active':''} onClick={()=>setLocale('en')}>English</button><button type="button" className={state.locale==='de'?'active':''} onClick={()=>setLocale('de')}>Deutsch</button></div></div><label className="setting-row checkbox-setting"><span><strong>Email notifications</strong><small>Receive borrower-facing request, document, terms and closing notifications.</small></span><input type="checkbox" checked={draft.notificationEmail} onChange={(e)=>setDraft({...draft,notificationEmail:e.target.checked})}/></label>{message&&<div className="success-banner" role="status">{message}</div>}<div className="form-actions"><button className="button primary">Save changes</button></div></form><Card title="Security & session" subtitle="Production SSO/MFA must be supplied by the shared identity service."><div className="security-list"><div><span><strong>Current session</strong><small>Borrower demo session · this browser</small></span><Status tone="success">Active</Status></div><div><span><strong>Multi-factor authentication</strong><small>Requires production identity service.</small></span><Status>Backend dependent</Status></div></div></Card></div>;
}
