import React, { useMemo, useState } from 'react';
import { Card, Field, PageHead, Status, euro } from '../components/UI';
import { useBorrowerStore } from '../state/store';

export function CapitalPage(){
  const {state,app,feature}=useBorrowerStore();
  const sources=state.advanced.sourcesUses.filter(x=>x.applicationId===app.id); const budget=state.advanced.constructionBudget.filter(x=>x.applicationId===app.id); const draws=state.advanced.drawRequests.filter(x=>x.applicationId===app.id); const inspections=state.advanced.inspections.filter(x=>x.applicationId===app.id);
  const isConstruction=useMemo(()=>{const p=state.advanced.workflowProfiles.find(w=>w.productIds.includes(app.financing.productId??''));return p?.kind==='construction'},[app.financing.productId,state.advanced.workflowProfiles]);
  const [drawOpen,setDrawOpen]=useState(false); const [amount,setAmount]=useState(500000); const [neededBy,setNeededBy]=useState('2026-09-15'); const [note,setNote]=useState('Monthly construction draw for certified progress and approved invoices.'); const [budgetLineId,setBudgetLineId]=useState(budget[0]?.id??'');
  const [inspectionOpen,setInspectionOpen]=useState(false); const [inspectionType,setInspectionType]=useState<'progress'|'completion'|'valuation'|'site'>('progress'); const [preferredDate,setPreferredDate]=useState('2026-09-08'); const [drawId,setDrawId]=useState('');
  const sourceTotal=sources.filter(x=>x.side==='source').reduce((s,x)=>s+x.amount,0), useTotal=sources.filter(x=>x.side==='use').reduce((s,x)=>s+x.amount,0);
  const submitDraw=(e:React.FormEvent)=>{e.preventDefault();feature({type:'create_draw',applicationId:app.id,requestedAmount:amount,neededBy,note,lineItems:budgetLineId?[{id:`LINE-${Date.now()}`,budgetLineId,amount,documentIds:[]}]:[]});setDrawOpen(false)};
  return <div className="route-stage"><PageHead eyebrow="Borrower / Capital" title="Draws, budget & inspections" subtitle="Construction-finance operations after structuring and closing: Sources & Uses, cost-to-complete, draw packages and inspection coordination." action={<div className="page-action-group"><button className="button secondary" onClick={()=>setInspectionOpen(true)}>Request inspection</button><button className="button primary" disabled={!isConstruction} onClick={()=>setDrawOpen(true)}>New draw request</button></div>}/>
    {!isConstruction&&<div className="demo-banner"><strong>Product-aware workflow:</strong><span>The active application is not currently classified as a construction/development workflow, so new draws are disabled. Switch to a development facility to use draw controls.</span></div>}
    <div className="capital-kpis"><Card><div className="kpi"><span>Total sources</span><strong>{euro(sourceTotal)}</strong><small>{euro(sources.filter(x=>x.side==='source').reduce((s,x)=>s+x.fundedAmount,0))} funded/committed</small></div></Card><Card><div className="kpi"><span>Total uses</span><strong>{euro(useTotal)}</strong><small>Variance {euro(sourceTotal-useTotal)}</small></div></Card><Card><div className="kpi"><span>Revised construction budget</span><strong>{euro(budget.reduce((s,x)=>s+x.revisedBudget,0))}</strong><small>{euro(budget.reduce((s,x)=>s+x.paidToDate,0))} paid to date</small></div></Card><Card><div className="kpi"><span>Draws / inspections</span><strong>{draws.length} / {inspections.length}</strong><small>Operational records linked to {app.id}</small></div></Card></div>
    <div className="two-column"><Card title="Sources & Uses" subtitle="Application capital stack and deployment plan."><div className="simple-ledger"><div className="ledger-head"><span>Side</span><span>Category</span><span>Amount</span><span>Funded</span></div>{sources.map(x=><div className="ledger-row" key={x.id}><Status tone={x.side==='source'?'info':'neutral'}>{x.side}</Status><span><strong>{x.category}</strong><small>{x.description}</small></span><strong>{euro(x.amount)}</strong><span>{euro(x.fundedAmount)}</span></div>)}</div></Card><Card title="Construction budget" subtitle="Original, revised, committed and paid-to-date amounts."><div className="budget-list">{budget.map(x=>{const used=x.revisedBudget?x.paidToDate/x.revisedBudget*100:0;return <div key={x.id}><span><strong>{x.costCode} · {x.category}</strong><small>Original {euro(x.originalBudget)} · committed {euro(x.committed)}</small></span><span className="budget-values"><strong>{euro(x.revisedBudget)}</strong><small>{used.toFixed(0)}% paid</small></span></div>})}</div></Card></div>
    <Card title="Draw requests" subtitle="Borrower requests remain subject to PiHub/lender review and any required inspection.">{draws.length===0?<p className="card-empty">No draw requests yet.</p>:<div className="draw-table"><div className="draw-head"><span>#</span><span>Requested</span><span>Needed by</span><span>Status</span><span>Action</span></div>{draws.map(d=><div className="draw-row" key={d.id}><strong>{d.number}</strong><span>{euro(d.requestedAmount)}</span><span>{d.neededBy}</span><Status tone={d.status==='funded'?'success':d.status==='rejected'?'danger':d.status==='draft'?'neutral':'info'}>{d.status.replaceAll('_',' ')}</Status><button className="button secondary" disabled={d.status!=='draft'} onClick={()=>feature({type:'submit_draw',drawRequestId:d.id})}>Submit</button></div>)}</div>}</Card>
    <Card title="Inspection workflow" subtitle="Site/valuation inspections can be linked to a draw without giving the borrower authority to mark an inspection complete.">{inspections.length===0?<p className="card-empty">No inspections requested.</p>:<div className="inspection-list">{inspections.map(i=><div key={i.id}><span><strong>{i.inspectionType.replace('_',' ')} inspection</strong><small>Preferred {i.preferredDate}{i.drawRequestId?` · linked to ${i.drawRequestId}`:''}</small></span><Status tone={i.status==='completed'?'success':i.status==='exception'?'danger':'info'}>{i.status}</Status></div>)}</div>}</Card>
    {drawOpen&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="draw-title"><div className="modal-head"><h2 id="draw-title">New draw request</h2><button className="icon-button" aria-label="Close" onClick={()=>setDrawOpen(false)}>×</button></div><form onSubmit={submitDraw}><Field label="Budget line"><select value={budgetLineId} onChange={e=>setBudgetLineId(e.target.value)} required>{budget.map(b=><option key={b.id} value={b.id}>{b.costCode} · {b.category}</option>)}</select></Field><Field label="Requested amount"><input type="number" min="1" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field><Field label="Funds needed by"><input type="date" value={neededBy} onChange={e=>setNeededBy(e.target.value)}/></Field><Field label="Draw note"><textarea rows={4} value={note} onChange={e=>setNote(e.target.value)}/></Field><div className="form-actions"><button className="button primary">Create draft</button><button type="button" className="button secondary" onClick={()=>setDrawOpen(false)}>Cancel</button></div></form></div></div>}
    {inspectionOpen&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="inspection-title"><div className="modal-head"><h2 id="inspection-title">Request inspection</h2><button className="icon-button" aria-label="Close" onClick={()=>setInspectionOpen(false)}>×</button></div><form onSubmit={e=>{e.preventDefault();feature({type:'request_inspection',applicationId:app.id,drawRequestId:drawId||undefined,inspectionType,preferredDate});setInspectionOpen(false)}}><Field label="Inspection type"><select value={inspectionType} onChange={e=>setInspectionType(e.target.value as typeof inspectionType)}><option value="progress">Progress</option><option value="completion">Completion</option><option value="valuation">Valuation</option><option value="site">Site</option></select></Field><Field label="Related draw"><select value={drawId} onChange={e=>setDrawId(e.target.value)}><option value="">No draw link</option>{draws.map(d=><option key={d.id} value={d.id}>Draw #{d.number}</option>)}</select></Field><Field label="Preferred date"><input type="date" value={preferredDate} onChange={e=>setPreferredDate(e.target.value)}/></Field><div className="form-actions"><button className="button primary">Request inspection</button><button type="button" className="button secondary" onClick={()=>setInspectionOpen(false)}>Cancel</button></div></form></div></div>}
  </div>
}
