import React, { useMemo, useState } from 'react';
import { Card, PageHead, Status, euro } from '../components/UI';
import { useBorrowerStore } from '../state/store';
import { createDataConnectionAuthorizationIntent } from '../services/platformApi';
import type { ConnectionProvider } from '../state/advancedModel';

const tone=(status:string)=>status==='connected'?'success':status==='error'?'danger':status==='expired'?'warning':'neutral';
export function ConnectionsPage(){
  const {state,feature,mode}=useBorrowerStore();
  const [notice,setNotice]=useState(''); const [busy,setBusy]=useState<string>();
  const connections=state.advanced.connections; const freshness=state.advanced.freshness; const integrations=state.advanced.integrations;
  const latest=useMemo(()=>state.advanced.cashFlow.slice().sort((a,b)=>b.period.localeCompare(a.period))[0],[state.advanced.cashFlow]);
  const connect=async(provider:ConnectionProvider,label:string,scope:string[],connectionId:string)=>{
    if(mode==='demo'){feature({type:'connect_source',provider,label,scope});return;}
    if(!['datev','finapi','erp_api'].includes(provider)){setNotice('This provider uses a server-managed integration and cannot be authorized directly from the browser.');return;}
    setBusy(connectionId);setNotice('');
    try{
      const intent=await createDataConnectionAuthorizationIntent({provider:provider as 'datev'|'finapi'|'erp_api',scopes:scope,returnTo:`${window.location.origin}/connections`});
      window.location.assign(intent.authorizationUrl);
    }catch(error){setNotice(error instanceof Error?error.message:'Unable to start the secure provider authorization flow.');setBusy(undefined);}
  };
  return <div className="route-stage"><PageHead eyebrow="Borrower / Data" title="Connections & data freshness" subtitle="Connect accounting, banking and enterprise data once, then make source, recency and borrower confirmation visible instead of repeatedly retyping the same numbers."/>
    {notice&&<div className="form-alert page-alert" role="alert">{notice}</div>}
    <div className="connection-kpis"><Card><div className="kpi"><span>Connected sources</span><strong>{connections.filter(c=>c.status==='connected').length}</strong><small>{connections.length} configured source types</small></div></Card><Card><div className="kpi"><span>Latest cash</span><strong>{latest?euro(latest.endingCash):'—'}</strong><small>{latest?`Snapshot ${latest.period}`:'Connect banking to monitor cash'}</small></div></Card><Card><div className="kpi"><span>Fresh data groups</span><strong>{freshness.filter(f=>f.status==='fresh').length}/{freshness.length}</strong><small>Borrower-confirmed or recently synchronized</small></div></Card><Card><div className="kpi"><span>Integration adapters</span><strong>{integrations.length}</strong><small>Open-source and enterprise provider boundaries</small></div></Card></div>
    <Card title="Financial data connections" subtitle={mode==='api'?'Provider authorization starts through PiHub so OAuth/PSD2/DATEV credentials never enter browser state.':'Demo buttons model consent and synchronization. Production switches to server-managed OAuth/consent intents.'}><div className="connection-grid">{connections.map(c=><article className="connection-card" key={c.id}><div className="connection-card-head"><span><strong>{c.label}</strong><small>{c.provider.replaceAll('_',' ')} · {c.scope.join(', ')}</small></span><Status tone={tone(c.status) as any}>{c.status.replaceAll('_',' ')}</Status></div><p>{c.lastSyncAt?`Last synchronized ${new Date(c.lastSyncAt).toLocaleString()}`:'Not yet synchronized.'}</p><div className="row-actions">{c.status==='connected'?<><button className="button primary" onClick={()=>feature({type:'sync_source',connectionId:c.id})}>Sync now</button><button className="button secondary" onClick={()=>feature({type:'disconnect_source',connectionId:c.id})}>Disconnect</button></>:<button className="button primary" disabled={busy===c.id} onClick={()=>void connect(c.provider,c.label,c.scope,c.id)}>{busy===c.id?'Starting secure consent…':'Connect'}</button>}</div></article>)}</div></Card>
    <div className="two-column"><Card title="Data freshness" subtitle="Imported data is not silently treated as borrower-submitted truth. Confirm or refresh stale groups."><div className="freshness-list">{freshness.map(f=><div key={f.id}><span><strong>{f.fieldGroup}</strong><small>{f.sourceLabel} · updated {new Date(f.lastUpdatedAt).toLocaleDateString()}</small></span><Status tone={f.status==='fresh'?'success':f.status==='stale'?'danger':'warning'}>{f.status.replace('_',' ')}</Status><button className="button secondary" disabled={f.status==='fresh'} onClick={()=>feature({type:'confirm_freshness',freshnessId:f.id})}>Confirm</button></div>)}</div></Card><Card title="Cash-flow monitoring" subtitle="Illustrative connected-account trend after funding. Production monitoring remains consent-scoped."><div className="cashflow-list">{state.advanced.cashFlow.map(x=><div key={x.id}><span><strong>{x.period}</strong><small>Inflows {euro(x.inflows)} · outflows {euro(x.outflows)}</small></span><span><strong>{euro(x.endingCash)}</strong><small>Debt service {euro(x.debtService)}</small></span></div>)}</div></Card></div>
    <Card title="ERP / API integration hub" subtitle="Provider-agnostic boundaries let PiHub use permissive open-source infrastructure where it helps without binding the Borrower UI to one vendor."><div className="integration-list">{integrations.map(i=><div key={i.id}><span><strong>{i.name}</strong><small>{i.provider} · {i.mode.replace('_',' ')} · {i.capabilities.join(', ')}</small></span><Status tone={i.status==='connected'?'success':i.status==='error'?'danger':'info'}>{i.status}</Status><button className="button secondary" onClick={()=>feature({type:'test_integration',connectorId:i.id})}>Test adapter</button></div>)}</div><p className="form-note">Prepared adapters: Docling for document parsing, Apache Fineract-compatible servicing, Temporal-compatible durable workflow orchestration, and API-isolated e-signature providers. Credentials and regulated production data never belong in the browser.</p></Card>
  </div>
}
