import React, { useMemo, useState } from 'react';
import { Card, PageHead, Status } from '../components/UI';
import { Icon } from '../components/Icons';
import { usePlatformIntegration } from '../platform/PlatformIntegrationContext';
import { useBorrowerStore } from '../state/store';
import { downloadText, toCsv } from '../utils/download';

export function DataRoomPage(){
  const {state,app,feature}=useBorrowerStore();
  const {projection,reuseVaultItem,workingId,error:platformError}=usePlatformIntegration();
  const [selected,setSelected]=useState<string[]>([]); const [folderName,setFolderName]=useState('');
  const docs=state.documents.filter(d=>d.applicationId===app.id);
  const intelligence=useMemo(()=>Object.fromEntries(state.advanced.documentIntelligence.map(x=>[x.documentId,x])),[state.advanced.documentIntelligence]);
  const canonicalVault=projection?.vaultItems?.length?projection.vaultItems:state.advanced.companyVault.map((item)=>({...item,linkedToApplication:docs.some((document)=>document.id===item.documentId)}));
  const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
  const bulkManifest=()=>{const rows=docs.filter(d=>selected.includes(d.id)).map(d=>({document_id:d.id,name:d.name,category:d.category,status:d.status,version:d.version,due_date:d.dueDate??'',size_bytes:d.size}));downloadText(`${app.id}-document-manifest.csv`,toCsv(rows),'text/csv;charset=utf-8');feature({type:'create_export',applicationId:app.id,format:'csv_manifest',includedSections:['document manifest']})};
  return <div className="route-stage"><PageHead eyebrow="Borrower / Data room" title="Advanced data room" subtitle="Reusable corporate documents, deal folders, bulk actions and document intelligence on top of the canonical PiHub document records." action={<div className="page-action-group"><button className="button secondary" disabled={!selected.length} onClick={()=>selected.forEach(id=>feature({type:'analyze_document',documentId:id}))}>Analyze selected</button><button className="button primary" disabled={!selected.length} onClick={bulkManifest}>Export manifest</button></div>}/>
    {platformError&&<div className="platform-warning" role="alert">{platformError}</div>}
    <div className="data-room-grid"><Card title="Folders" subtitle="Organize the borrower-facing workspace without changing the canonical document identity."><div className="folder-list">{state.advanced.dataRoomFolders.filter(f=>!f.applicationId||f.applicationId===app.id).map(f=><div key={f.id}><span className="folder-icon"><Icon name="document" size={15}/></span><span><strong>{f.name}</strong><small>{f.purpose.replace('_',' ')}</small></span></div>)}</div><div className="inline-control"><input value={folderName} onChange={e=>setFolderName(e.target.value)} placeholder="New folder name"/><button className="button secondary" disabled={!folderName.trim()} onClick={()=>{feature({type:'create_folder',name:folderName,purpose:'application',applicationId:app.id});setFolderName('')}}>Create</button></div></Card><Card title="Company vault" subtitle="Reuse one accepted, malware-cleared corporate document across financing applications without copying its file or version history.">{canonicalVault.length===0?<p className="card-empty">No reusable documents yet. Add a current corporate document from the table below.</p>:<div className="vault-list">{canonicalVault.map(v=><div key={v.id}><span><strong>{v.label}</strong><small>{v.category}{v.validUntil?` · valid until ${v.validUntil}`:''}</small></span><div className="row-actions"><Status tone={v.linkedToApplication?'success':'info'}>{v.linkedToApplication?'Used in this application':'Reusable'}</Status>{!v.linkedToApplication&&<button className="button secondary" disabled={workingId===`vault:${v.id}`} onClick={()=>void reuseVaultItem(v.id).catch(()=>undefined)}>{workingId===`vault:${v.id}`?'Linking…':'Reuse in application'}</button>}</div></div>)}</div>}</Card></div>
    <Card title="Application documents" subtitle="Select rows for bulk processing. Intelligence results remain reviewable and do not overwrite submitted borrower data automatically."><div className="room-table"><div className="room-head"><span></span><span>Document</span><span>Status</span><span>Intelligence</span><span>Actions</span></div>{docs.map(d=>{const a=intelligence[d.id];return <div className="room-row" key={d.id}><input type="checkbox" aria-label={`Select ${d.name}`} checked={selected.includes(d.id)} onChange={()=>toggle(d.id)}/><span><strong>{d.name}</strong><small>{d.category} · v{d.version}{d.dueDate?` · due ${d.dueDate}`:''}</small></span><Status tone={d.status==='accepted'?'success':d.status==='rejected'||d.status==='expired'?'danger':d.status==='required'?'warning':'info'}>{d.status.replace('_',' ')}</Status><span className="doc-intel">{a?<><strong>{a.predictedCategory??'Classified'}</strong><small>{a.confidence?`${Math.round(a.confidence*100)}% confidence`:a.status}{a.warnings.length?` · ${a.warnings.length} warning(s)`:''}</small></>:<small>Not analyzed</small>}</span><div className="row-actions"><button className="button secondary" onClick={()=>feature({type:'analyze_document',documentId:d.id})}>Analyze</button><button className="button secondary" disabled={canonicalVault.some(v=>v.documentId===d.id)} onClick={()=>feature({type:'add_vault_item',documentId:d.id,label:d.name,category:d.category})}>Add to vault</button></div></div>})}</div></Card>
    <Card title="Document intelligence review" subtitle="The production adapter can use Docling or another approved document-processing service; extracted values still require policy/borrower review before becoming canonical financial data.">{state.advanced.documentIntelligence.length===0?<p className="card-empty">Analyze a document to create a review record.</p>:<div className="intelligence-list">{state.advanced.documentIntelligence.map(a=>{const d=state.documents.find(x=>x.id===a.documentId);return <div key={a.id}><span><strong>{d?.name??a.documentId}</strong><small>{a.engine} · {a.status.replace('_',' ')}</small></span><div>{Object.entries(a.extractedFields).slice(0,4).map(([k,v])=><span className="tag" key={k}>{k}: {String(v)}</span>)}</div>{a.warnings.length?<p>{a.warnings.join(' ')}</p>:<Status tone="success">No demo warnings</Status>}</div>})}</div>}</Card>
  </div>
}
