import React, { useState } from 'react';
import { Card, Field, PageHead, Status } from '../components/UI';
import { useBorrowerStore } from '../state/store';
import type { DisclosureGrant } from '../state/advancedModel';

export function DisclosuresPage(){
  const {state,app,feature}=useBorrowerStore(); const [open,setOpen]=useState(false); const [providerName,setProviderName]=useState(''); const [providerType,setProviderType]=useState<DisclosureGrant['providerType']>('lender'); const [purpose,setPurpose]=useState('Evaluate the financing opportunity and supporting due diligence.'); const [documents,setDocuments]=useState<string[]>([]); const [expiresAt,setExpiresAt]=useState('');
  const appDocs=state.documents.filter(d=>d.applicationId===app.id&&d.status!=='required');
  const submit=(e:React.FormEvent)=>{e.preventDefault();if(!providerName.trim()||!documents.length)return;feature({type:'create_disclosure',applicationId:app.id,providerName,providerType,documentIds:documents,purpose,expiresAt:expiresAt||undefined});setOpen(false);setProviderName('');setDocuments([])};
  return <div className="route-stage"><PageHead eyebrow="Borrower / Consent" title="Disclosure & consent center" subtitle="A borrower-visible record of who may receive a deal or document, why it is being shared and whether that permission remains active." action={<button className="button primary" onClick={()=>setOpen(true)}>Grant disclosure consent</button>}/>
    <div className="demo-banner"><strong>Privacy boundary:</strong><span>Consent here controls borrower-visible disclosure intent. Production enforcement must still happen server-side against canonical application/document access grants.</span></div>
    <Card title="Disclosure history" subtitle={`${state.advanced.disclosures.filter(d=>d.applicationId===app.id).length} consent record(s) for ${app.id}.`}>{state.advanced.disclosures.filter(d=>d.applicationId===app.id).length===0?<p className="card-empty">No third-party disclosure consent recorded for this application.</p>:<div className="disclosure-list">{state.advanced.disclosures.filter(d=>d.applicationId===app.id).map(d=><div key={d.id}><span><strong>{d.providerName}</strong><small>{d.providerType.replace('_',' ')} · {d.documentIds.length} document(s) · {d.purpose}</small><small>{d.consentedAt?`Consented ${new Date(d.consentedAt).toLocaleString()}`:''}{d.expiresAt?` · expires ${d.expiresAt}`:''}</small></span><Status tone={d.status==='active'?'success':d.status==='revoked'?'danger':'warning'}>{d.status}</Status><button className="button secondary" disabled={d.status!=='active'} onClick={()=>feature({type:'revoke_disclosure',disclosureId:d.id})}>Revoke</button></div>)}</div>}</Card>
    {open&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="disclosure-title"><div className="modal-head"><h2 id="disclosure-title">Grant disclosure consent</h2><button className="icon-button" aria-label="Close" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={submit}><Field label="Provider / recipient"><input value={providerName} onChange={e=>setProviderName(e.target.value)} required placeholder="Financing provider or diligence adviser"/></Field><Field label="Recipient type"><select value={providerType} onChange={e=>setProviderType(e.target.value as DisclosureGrant['providerType'])}><option value="lender">Lender</option><option value="investor">Investor</option><option value="adviser">Adviser</option><option value="service_provider">Service provider</option></select></Field><Field label="Purpose"><textarea rows={3} value={purpose} onChange={e=>setPurpose(e.target.value)} required/></Field><Field label="Documents"><div className="checkbox-list">{appDocs.map(d=><label key={d.id}><input type="checkbox" checked={documents.includes(d.id)} onChange={()=>setDocuments(v=>v.includes(d.id)?v.filter(x=>x!==d.id):[...v,d.id])}/><span>{d.name}</span></label>)}</div></Field><Field label="Optional expiry"><input type="date" value={expiresAt} onChange={e=>setExpiresAt(e.target.value)}/></Field><div className="form-actions"><button className="button primary" disabled={!documents.length||!providerName.trim()}>Record consent</button><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button></div></form></div></div>}
  </div>
}
