import React, { useState } from 'react';
import { Card, Field, PageHead, Status } from '../components/UI';
import { useBorrowerStore } from '../state/store';

export function NegotiationPage(){
  const {state,app,feature}=useBorrowerStore(); const terms=state.terms.filter(t=>t.applicationId===app.id); const [termId,setTermId]=useState(terms[0]?.id??''); const [message,setMessage]=useState(''); const [counterField,setCounterField]=useState('Margin'); const [counterValue,setCounterValue]=useState('5.25%'); const [rationale,setRationale]=useState('Requesting lower pricing based on updated sponsor equity and current project progress.'); const [title,setTitle]=useState('Facility agreement signing package'); const [signers,setSigners]=useState(state.profile.email); const [provider,setProvider]=useState<'demo'|'documenso'>('demo');
  const thread=state.advanced.negotiations.find(n=>n.termSheetId===termId); const envelopes=state.advanced.signatureEnvelopes.filter(e=>e.applicationId===app.id);
  return <div className="route-stage"><PageHead eyebrow="Borrower / Terms" title="Negotiation & e-signature" subtitle="Ask questions against a term sheet, propose borrower counters, compare revisions and track signing packages without exposing internal lender discussions."/>
    <div className="negotiation-layout"><Card title="Commercial discussion" subtitle="Every borrower message and counter remains linked to the selected term sheet."><Field label="Indicative offer"><select value={termId} onChange={e=>setTermId(e.target.value)}>{terms.map(t=><option key={t.id} value={t.id}>{t.provider} · {t.id}</option>)}</select></Field><div className="conversation-box">{thread?.messages.length?thread.messages.map(m=><div className={`conversation-message ${m.author}`} key={m.id}><strong>{m.author==='borrower'?'Borrower':'PiHub'}</strong><p>{m.body}</p><small>{new Date(m.createdAt).toLocaleString()}</small></div>):<p className="card-empty">No messages on this term yet.</p>}</div><form className="message-compose" onSubmit={e=>{e.preventDefault();if(!termId||!message.trim())return;feature({type:'send_negotiation_message',termSheetId:termId,applicationId:app.id,body:message});setMessage('')}}><textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask PiHub a question about pricing, security, covenants or execution."/><button className="button primary" disabled={!message.trim()}>Send</button></form></Card>
      <Card title="Commercial counter" subtitle="Counters are explicit borrower proposals, not silent edits to lender terms."><form onSubmit={e=>{e.preventDefault();if(!termId)return;feature({type:'submit_counter',termSheetId:termId,applicationId:app.id,field:counterField,requestedValue:counterValue,rationale})}}><Field label="Term"><select value={counterField} onChange={e=>setCounterField(e.target.value)}><option>Margin</option><option>Fees</option><option>Facility amount</option><option>Tenor</option><option>Amortization</option><option>Security</option><option>Covenant</option></select></Field><Field label="Requested value"><input value={counterValue} onChange={e=>setCounterValue(e.target.value)}/></Field><Field label="Rationale"><textarea rows={5} value={rationale} onChange={e=>setRationale(e.target.value)}/></Field><button className="button primary">Propose counter</button></form>{thread?.counters.length?<div className="counter-list">{thread.counters.map(c=><div key={c.id}><span><strong>{c.field}: {c.requestedValue}</strong><small>{c.rationale}</small></span><Status tone={c.status==='accepted'?'success':c.status==='declined'?'danger':'warning'}>{c.status}</Status></div>)}</div>:null}</Card></div>
    <Card title="Signing packages" subtitle="The demo adapter simulates signer progress. Production can use a self-hosted/API e-sign provider such as Documenso without embedding copyleft server code into this frontend."><form className="signature-create" onSubmit={e=>{e.preventDefault();feature({type:'create_signature_envelope',applicationId:app.id,title,documentIds:state.documents.filter(d=>d.applicationId===app.id&&d.status!=='required').slice(0,2).map(d=>d.id),signerEmails:signers.split(',').map(x=>x.trim()).filter(Boolean),provider})}}><Field label="Package title"><input value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Provider"><select value={provider} onChange={e=>setProvider(e.target.value as typeof provider)}><option value="demo">PiHub demo adapter</option><option value="documenso">Documenso API</option></select></Field><Field label="Signer emails"><input value={signers} onChange={e=>setSigners(e.target.value)} placeholder="finance@example.com, legal@example.com"/></Field><button className="button primary">Create signing package</button></form><div className="envelope-list">{envelopes.map(env=><div key={env.id}><span><strong>{env.title}</strong><small>{env.provider} · {env.documentIds.length} document(s)</small></span><Status tone={env.status==='completed'?'success':env.status==='voided'?'danger':'info'}>{env.status.replace('_',' ')}</Status><div className="signer-list">{env.signers.map(s=><button className="button secondary" key={s.email} disabled={s.status==='signed'||env.provider!=='demo'} title={env.provider!=='demo'?'External provider status is authoritative in production.':'Simulate signer completion in demo mode.'} onClick={()=>feature({type:'sign_envelope_demo',envelopeId:env.id,signerEmail:s.email})}>{s.name}: {s.status}</button>)}</div></div>)}</div></Card>
  </div>
}
