import React, { useMemo, useState } from 'react';
import { Card, EmptyState, Field, PageHead, Status, euro } from '../components/UI';
import { useBorrowerStore } from '../state/store';
import type { PaymentInstruction } from '../state/advancedModel';
import type { ServicingRequest } from '../state/model';
import { downloadText, toCsv } from '../utils/download';

const pTone=(s:string)=>s==='paid'?'success':s==='overdue'?'danger':s==='due'?'warning':'neutral';
export function PaymentsPage(){
  const {state,app,feature,createServicingRequest,reportPaymentMade}=useBorrowerStore();
  const facility=state.facilities.find((f)=>f.applicationId===app.id)??state.facilities[0];
  const schedule=useMemo(()=>facility?state.paymentSchedule.filter(p=>p.facilityId===facility.id).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)):[],[state.paymentSchedule,facility?.id]);
  const instructions=facility?state.advanced.paymentInstructions.filter(p=>p.facilityId===facility.id):[];
  const statements=facility?state.advanced.statements.filter(s=>s.facilityId===facility.id):[];
  const [instruction,setInstruction]=useState({label:'Operating account',ibanMasked:'DE•• •••• •••• •••• 1234 00',accountHolder:state.organization.name,mandateType:'manual_transfer' as PaymentInstruction['mandateType']});
  const [requestType,setRequestType]=useState<ServicingRequest['type']>('partial_prepayment'); const [requestText,setRequestText]=useState(''); const [notice,setNotice]=useState('');
  if(!facility)return <div className="route-stage"><PageHead eyebrow="Borrower / Payments" title="Payments & statements" subtitle="Facility repayment and account instructions."/><EmptyState title="No funded facility" body="Payment schedules become available after funding."/></div>;
  const exportSchedule=()=>downloadText(`${facility.id}-repayment-schedule.csv`,toCsv(schedule.map(p=>({dueDate:p.dueDate,principal:p.principal,interest:p.interest,fees:p.fees,status:p.status,paidAt:p.paidAt??''}))), 'text/csv;charset=utf-8');
  return <div className="route-stage"><PageHead eyebrow="Borrower / Facility" title="Payments & statements" subtitle="Repayment schedule, account instructions, statements and formal facility transaction requests." action={<button className="button secondary" onClick={exportSchedule}>Export schedule CSV</button>}/>
    {notice&&<div className="success-banner" role="status">{notice}</div>}
    <div className="payment-kpis"><Card><div className="kpi"><span>Outstanding</span><strong>{euro(facility.outstandingAmount)}</strong><small>{facility.id}</small></div></Card><Card><div className="kpi"><span>Scheduled payments</span><strong>{schedule.length}</strong><small>{schedule.filter(p=>p.status==='paid').length} confirmed paid</small></div></Card><Card><div className="kpi"><span>Maturity</span><strong>{facility.maturityDate}</strong><small>{facility.provider}</small></div></Card></div>
    <Card title="Repayment schedule" subtitle="Payment status remains provider/PiHub-authoritative. Borrower payment notices request reconciliation rather than rewriting settlement truth."><div className="payment-table data-table"><div className="data-head"><span>Due</span><span>Principal</span><span>Interest + fees</span><span>Status</span><span>Action</span></div>{schedule.map((p)=><div className="data-row" key={p.id}><span>{p.dueDate}</span><span>{euro(p.principal)}</span><span>{euro(p.interest+p.fees)}</span><Status tone={pTone(p.status) as any}>{p.status}</Status><button className="button secondary" disabled={p.status==='paid'} onClick={()=>{reportPaymentMade(p.id,`Borrower payment notice submitted for ${p.dueDate}`);setNotice('Payment notice sent for PiHub/provider reconciliation.')}}>Report payment</button></div>)}</div></Card>
    <div className="two-column"><Card title="Payment instructions" subtitle="Sensitive account changes require verification before becoming active."><form onSubmit={(e)=>{e.preventDefault();feature({type:'create_payment_instruction',facilityId:facility.id,...instruction});setNotice('Payment instruction submitted for verification.')}}><Field label="Label"><input value={instruction.label} onChange={(e)=>setInstruction({...instruction,label:e.target.value})}/></Field><Field label="Account holder"><input value={instruction.accountHolder} onChange={(e)=>setInstruction({...instruction,accountHolder:e.target.value})}/></Field><Field label="IBAN (masked or tokenized in demo)"><input value={instruction.ibanMasked} onChange={(e)=>setInstruction({...instruction,ibanMasked:e.target.value})}/></Field><Field label="Payment method"><select value={instruction.mandateType} onChange={(e)=>setInstruction({...instruction,mandateType:e.target.value as PaymentInstruction['mandateType']})}><option value="manual_transfer">Manual transfer</option><option value="sepa_direct_debit">SEPA direct debit</option></select></Field><div className="form-actions"><button className="button primary">Submit for verification</button></div></form><div className="instruction-list">{instructions.map((i)=><div key={i.id}><span><strong>{i.label}</strong><small>{i.ibanMasked} · {i.mandateType.replaceAll('_',' ')}</small></span><Status tone={i.status==='active'?'success':'warning'}>{i.status.replaceAll('_',' ')}</Status><button className="button secondary" disabled={i.status!=='active'||i.isDefault} onClick={()=>feature({type:'set_default_payment_instruction',instructionId:i.id})}>{i.isDefault?'Default':'Make default'}</button></div>)}</div></Card>
    <Card title="Facility transaction request" subtitle="Increase, drawdown, rollover, prepayment, payoff, refinance and repayment-account changes all enter a governed servicing workflow."><form onSubmit={(e)=>{e.preventDefault();if(!requestText.trim())return;createServicingRequest({facilityId:facility.id,type:requestType,subject:requestType.replaceAll('_',' '),description:requestText.trim()});setRequestText('');setNotice('Facility transaction request submitted for PiHub review.')}}><Field label="Request type"><select value={requestType} onChange={(e)=>setRequestType(e.target.value as ServicingRequest['type'])}><option value="facility_increase">Facility increase</option><option value="additional_drawdown">Additional drawdown</option><option value="rollover">Rollover</option><option value="extension">Extension</option><option value="partial_prepayment">Partial prepayment</option><option value="full_repayment">Full repayment</option><option value="refinance">Refinance</option><option value="payment_account_change">Change payment account</option><option value="payoff">Formal payoff / discharge</option></select></Field><Field label="Request details"><textarea rows={5} value={requestText} onChange={(e)=>setRequestText(e.target.value)} placeholder="Amount, target date, reason and supporting references." required/></Field><div className="form-actions"><button className="button primary">Submit request</button></div></form></Card></div>
    <Card title="Statements" subtitle="Period-level balances, principal, interest and fees. Production statements should be generated from the authoritative servicing ledger.">{statements.length===0?<EmptyState title="No statements yet" body="Statements will appear after a completed servicing period."/>:<div className="statement-list">{statements.map((s)=><div key={s.id}><span><strong>{s.periodStart} – {s.periodEnd}</strong><small>Generated {new Date(s.generatedAt).toLocaleDateString()}</small></span><span><strong>{euro(s.closingBalance)}</strong><small>Closing balance</small></span><button className="button secondary" onClick={()=>downloadText(`${s.id}.csv`,toCsv([{periodStart:s.periodStart,periodEnd:s.periodEnd,openingBalance:s.openingBalance,principalPaid:s.principalPaid,interestPaid:s.interestPaid,feesPaid:s.feesPaid,closingBalance:s.closingBalance}]),'text/csv;charset=utf-8')}>Download CSV</button></div>)}</div>}</Card>
  </div>;
}
