import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card, Field, PageHead, Status, euro } from '../components/UI';
import { useBorrowerStore } from '../state/store';
import { scenarioMetrics } from '../state/advanced';

export function ScenarioLabPage(){
  const {state,app,feature}=useBorrowerStore();
  const [name,setName]=useState('Base financing case'); const [amount,setAmount]=useState(app.financing.amount||18000000); const [tenor,setTenor]=useState(app.financing.tenorMonths||24); const [referenceRate,setReferenceRate]=useState(2.7); const [margin,setMargin]=useState(575); const [fees,setFees]=useState(1.5); const [amortization,setAmortization]=useState(0); const [equity,setEquity]=useState(app.financing.sponsorEquity||6500000); const [value,setValue]=useState(app.project.valuation||45000000); const [noi,setNoi]=useState(2800000);
  const draft=useMemo(()=>({id:'draft',applicationId:app.id,name,amount,tenorMonths:tenor,referenceRatePct:referenceRate,marginBps:margin,feesPct:fees,amortizationPct:amortization,equity,propertyValue:value,projectedAnnualNOI:noi,createdAt:new Date().toISOString()}),[app.id,name,amount,tenor,referenceRate,margin,fees,amortization,equity,value,noi]); const m=scenarioMetrics(draft);
  const save=()=>feature({type:'save_scenario',scenario:{applicationId:app.id,name,amount,tenorMonths:tenor,referenceRatePct:referenceRate,marginBps:margin,feesPct:fees,amortizationPct:amortization,equity,propertyValue:value,projectedAnnualNOI:noi}});
  return <div className="route-stage"><PageHead eyebrow="Borrower / Decision tools" title="Financing scenario lab" subtitle="Stress amount, rate, fees, tenor, amortization and equity before deciding which financing structure best fits the project." action={<button className="button primary" onClick={save}>Save scenario</button>}/>
    <div className="scenario-layout"><Card title="Scenario assumptions" subtitle="Borrower-side decision support only. This does not change a lender term sheet."><div className="form-grid three"><Field label="Scenario name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Facility amount"><input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field><Field label="Tenor (months)"><input type="number" value={tenor} onChange={e=>setTenor(Number(e.target.value))}/></Field><Field label="Reference rate %"><input type="number" step="0.05" value={referenceRate} onChange={e=>setReferenceRate(Number(e.target.value))}/></Field><Field label="Margin (bps)"><input type="number" value={margin} onChange={e=>setMargin(Number(e.target.value))}/></Field><Field label="Fees %"><input type="number" step="0.05" value={fees} onChange={e=>setFees(Number(e.target.value))}/></Field><Field label="Annual amortization %"><input type="number" step="0.5" value={amortization} onChange={e=>setAmortization(Number(e.target.value))}/></Field><Field label="Sponsor equity"><input type="number" value={equity} onChange={e=>setEquity(Number(e.target.value))}/></Field><Field label="Property / enterprise value"><input type="number" value={value} onChange={e=>setValue(Number(e.target.value))}/></Field><Field label="Projected annual NOI / debt service cash"><input type="number" value={noi} onChange={e=>setNoi(Number(e.target.value))}/></Field></div></Card><Card title="Scenario impact" subtitle="Indicative arithmetic for comparing financing choices."><div className="metric-grid"><div><span>All-in annual rate</span><strong>{m.annualRate.toFixed(2)}%</strong></div><div><span>LTV</span><strong>{m.ltv.toFixed(1)}%</strong></div><div><span>LTC proxy</span><strong>{m.ltc.toFixed(1)}%</strong></div><div><span>Annual debt service</span><strong>{euro(m.debtService)}</strong></div><div><span>DSCR proxy</span><strong>{m.dscr.toFixed(2)}x</strong></div><div><span>Total interest</span><strong>{euro(m.totalInterest)}</strong></div><div><span>Upfront fees</span><strong>{euro(m.fees)}</strong></div><div><span>All-in cost</span><strong>{euro(m.allInCost)}</strong></div></div><div className="stress-row"><button className="button secondary" onClick={()=>setReferenceRate(v=>v+1)}>Stress +100 bps</button><button className="button secondary" onClick={()=>setReferenceRate(v=>v+2)}>Stress +200 bps</button><button className="button secondary" onClick={()=>setReferenceRate(2.7)}>Reset rate</button></div></Card></div>
    <Card title="Offer impact comparison" subtitle="Compare price, leverage and term-sheet consequences rather than rate alone."><div className="offer-impact-table"><div className="offer-impact-head"><span>Provider</span><span>Amount</span><span>Rate / margin</span><span>Fees</span><span>LTV</span><span>Tenor</span><span></span></div>{state.terms.filter(t=>t.applicationId===app.id).map(t=><div className="offer-impact-row" key={t.id}><span><strong>{t.provider}</strong><Status tone={t.status==='accepted'?'success':t.status==='rejected'?'danger':'info'}>{t.status}</Status></span><span>{euro(t.amount)}</span><span>{t.referenceRate} + {(t.marginBps/100).toFixed(2)}%</span><span>{t.fees}%</span><span>{t.ltv}%</span><span>{t.tenorMonths}m</span><Link className="button secondary" to="/negotiation">Discuss</Link></div>)}</div></Card>
    {state.advanced.scenarios.length>0&&<Card title="Saved scenarios" subtitle="Use saved cases as borrower-side decision checkpoints."><div className="scenario-list">{state.advanced.scenarios.filter(s=>s.applicationId===app.id).map(s=>{const sm=scenarioMetrics(s);return <div key={s.id}><span><strong>{s.name}</strong><small>{euro(s.amount)} · {s.tenorMonths}m · {(s.referenceRatePct+s.marginBps/100).toFixed(2)}% annual rate</small></span><span><strong>{sm.ltv.toFixed(1)}% LTV</strong><small>{euro(sm.allInCost)} all-in cost</small></span></div>})}</div></Card>}
  </div>
}
