import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Card, Field, PageHead, Status } from '../components/UI';
import { Icon } from '../components/Icons';
import { useBorrowerStore } from '../state/store';
import type { TeamMember } from '../state/model';
import type { ExternalProfessional } from '../state/advancedModel';

export function TeamPage() {
  const { state, inviteTeamMember, resendTeamInvitation, updateTeamMember, feature }=useBorrowerStore();
  const [open,setOpen]=useState(false); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [role,setRole]=useState<TeamMember['role']>('viewer'); const [error,setError]=useState('');
  const [professionalOpen,setProfessionalOpen]=useState(false);
  const [professional,setProfessional]=useState({name:'',email:'',profession:'accountant' as ExternalProfessional['profession'],expiresAt:new Date(Date.now()+30*86400000).toISOString().slice(0,10),applicationIds:[state.activeApplicationId],permissions:['view_documents'] as ExternalProfessional['permissions']});
  const invite=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()||!email.includes('@')){setError('Enter a name and valid email address.');return;}inviteTeamMember({name,email,role});setName('');setEmail('');setRole('viewer');setOpen(false);setError('');};
  return <div className="route-stage"><PageHead eyebrow="Borrower / Organization" title="Organization & team" subtitle="Invite colleagues and define their intended Borrower workspace role. Production permissions must still be enforced by the backend." action={<button className="button primary" onClick={()=>setOpen(true)}>Invite team member</button>}/>
    <div className="demo-banner"><strong>RBAC boundary:</strong><span>This UI can model roles and invitations, but production authorization must be server-enforced by Admin/Platform.</span></div>

    <Card title="Organization verification" subtitle="Borrower-visible compliance requirements only. Internal compliance decisions remain in Admin."><div className="verification-list"><div><span><strong>Company identity</strong><small>Legal name, registration number and address information</small></span><Status tone="success">Provided</Status><Link className="button secondary" to="/company">Review</Link></div><div><span><strong>Ownership / UBO information</strong><small>Ownership and beneficial-owner evidence may be requested by PiHub Compliance.</small></span><Status tone={state.organization.verificationStatus==='verified'?'success':'warning'}>{state.organization.verificationStatus==='verified'?'Verified':'Pending review'}</Status><Link className="button secondary" to="/documents">Documents</Link></div><div><span><strong>Compliance documents</strong><small>Registration extracts, proof of address and authorization evidence.</small></span><Status tone="warning">Action may be required</Status><Link className="button secondary" to="/documents">Open</Link></div></div></Card>
    <Card title="External professional access" subtitle="Invite accountants, lawyers, tax advisers, architects, contractors or brokers with time-limited deal-specific permissions." action={<button className="button secondary" onClick={()=>setProfessionalOpen(true)}>Invite professional</button>}>
      {state.advanced.professionals.length===0?<p className="muted">No external professionals currently have access.</p>:<div className="professional-list">{state.advanced.professionals.map((person)=><div className="professional-row" key={person.id}><span><strong>{person.name}</strong><small>{person.email} · {person.profession.replaceAll('_',' ')}</small><small>{person.permissions.map((p)=>p.replaceAll('_',' ')).join(' · ')} · expires {person.expiresAt}</small></span><Status tone={person.status==='active'?'success':person.status==='revoked'?'danger':'warning'}>{person.status}</Status><button className="button secondary" disabled={person.status==='revoked'} onClick={()=>feature({type:'revoke_professional',professionalId:person.id})}>Revoke</button></div>)}</div>}
    </Card>
    <Card title={state.organization.name} subtitle={`Verification: ${state.organization.verificationStatus.replace('_',' ')}`}><div className="team-table data-table"><div className="data-head"><span>Member</span><span>Role</span><span>Status</span><span>Actions</span></div>{state.team.map((member)=><div className="data-row" key={member.id}><div><strong>{member.name}</strong><small>{member.email}</small></div><select aria-label={`Role for ${member.name}`} value={member.role} disabled={member.role==='owner'} onChange={(e)=>updateTeamMember(member.id,{role:e.target.value as TeamMember['role']})}><option value="owner">Owner</option><option value="editor">Editor</option><option value="finance">Finance</option><option value="legal">Legal</option><option value="signatory">Signatory</option><option value="viewer">Viewer</option></select><Status tone={member.status==='active'?'success':member.status==='invited'?'warning':'danger'}>{member.status}</Status><div className="row-actions">{member.status==='invited'&&<button className="button secondary" onClick={()=>resendTeamInvitation(member.id)}>Resend invite</button>}<button className="button secondary" disabled={member.role==='owner'} onClick={()=>updateTeamMember(member.id,{status:member.status==='revoked'?'active':'revoked'})}>{member.status==='revoked'?'Restore':'Revoke'}</button></div></div>)}</div></Card>
    {professionalOpen&&<div className="modal-backdrop" role="presentation" onMouseDown={(e)=>{if(e.currentTarget===e.target)setProfessionalOpen(false)}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="professional-title"><div className="modal-head"><h2 id="professional-title">Invite external professional</h2><button className="icon-button" aria-label="Close" onClick={()=>setProfessionalOpen(false)}><Icon name="x"/></button></div><form onSubmit={(e)=>{e.preventDefault();if(!professional.name.trim()||!professional.email.includes('@'))return;feature({type:'invite_professional',professional:{...professional,applicationIds:professional.applicationIds.length?professional.applicationIds:[state.activeApplicationId]}});setProfessionalOpen(false);setProfessional({...professional,name:'',email:''})}}><Field label="Name"><input value={professional.name} onChange={(e)=>setProfessional({...professional,name:e.target.value})} required/></Field><Field label="Email"><input type="email" value={professional.email} onChange={(e)=>setProfessional({...professional,email:e.target.value})} required/></Field><Field label="Profession"><select value={professional.profession} onChange={(e)=>setProfessional({...professional,profession:e.target.value as ExternalProfessional['profession']})}><option value="accountant">Accountant</option><option value="lawyer">Lawyer</option><option value="tax_adviser">Tax adviser</option><option value="architect">Architect</option><option value="contractor">Contractor</option><option value="broker">Broker</option><option value="other">Other</option></select></Field><Field label="Access expires"><input type="date" value={professional.expiresAt} onChange={(e)=>setProfessional({...professional,expiresAt:e.target.value})} required/></Field><fieldset className="permission-fieldset"><legend>Permissions</legend>{(['view_documents','upload_documents','respond_requests','view_financials'] as ExternalProfessional['permissions']).map((permission)=><label key={permission}><input type="checkbox" checked={professional.permissions.includes(permission)} onChange={(e)=>setProfessional({...professional,permissions:e.target.checked?[...professional.permissions,permission]:professional.permissions.filter((p)=>p!==permission)})}/><span>{permission.replaceAll('_',' ')}</span></label>)}</fieldset><div className="form-actions"><button className="button primary">Send professional invitation</button><button type="button" className="button secondary" onClick={()=>setProfessionalOpen(false)}>Cancel</button></div></form></div></div>}
    {open&&<div className="modal-backdrop" role="presentation" onMouseDown={(e)=>{if(e.currentTarget===e.target)setOpen(false)}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="invite-title"><div className="modal-head"><h2 id="invite-title">Invite team member</h2><button className="icon-button" aria-label="Close" onClick={()=>setOpen(false)}><Icon name="x"/></button></div><form onSubmit={invite}><Field label="Name"><input value={name} onChange={(e)=>setName(e.target.value)}/></Field><Field label="Email" error={error}><input type="email" value={email} onChange={(e)=>{setEmail(e.target.value);setError('')}}/></Field><Field label="Role"><select value={role} onChange={(e)=>setRole(e.target.value as TeamMember['role'])}><option value="editor">Editor</option><option value="finance">Finance</option><option value="legal">Legal</option><option value="signatory">Signatory</option><option value="viewer">Viewer</option></select></Field><div className="form-actions"><button className="button primary">Send invitation</button><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button></div></form></div></div>}
  </div>;
}
