-- Reconciles the managed PiHub runtime foundation that was validated in Supabase
-- before the source-controlled BFF cutover. Safe to run after 0011.

create table if not exists public.borrower_workspace_states (
  organization_id uuid primary key references public.organizations(id) on delete cascade,
  snapshot jsonb not null,
  revision bigint not null default 1 check (revision > 0),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.borrower_command_journal (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  application_id text references public.applications(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  idempotency_key text not null,
  command text not null,
  aggregate_id text,
  payload jsonb not null default '{}'::jsonb,
  revision bigint not null check (revision > 0),
  created_at timestamptz not null default now(),
  unique(user_id,idempotency_key), unique(organization_id,revision)
);
create index if not exists borrower_command_journal_org_revision_idx on public.borrower_command_journal(organization_id,revision);
create index if not exists borrower_command_journal_application_idx on public.borrower_command_journal(application_id,revision) where application_id is not null;
alter table public.borrower_workspace_states enable row level security;
alter table public.borrower_command_journal enable row level security;
revoke all on public.borrower_workspace_states,public.borrower_command_journal from public,anon,authenticated;
grant all on public.borrower_workspace_states,public.borrower_command_journal to service_role;

create or replace function private.primary_borrower_membership(caller_user_id uuid)
returns table(organization_id uuid,organization_name text,member_role text,verification_status text)
language sql stable security definer set search_path='' as $$
 select o.id,o.legal_name,m.role::text,o.verification_status from public.organization_members m join public.organizations o on o.id=m.organization_id where m.user_id=caller_user_id and m.status='active' order by case m.role::text when 'owner' then 0 else 1 end,o.created_at limit 1
$$;
revoke all on function private.primary_borrower_membership(uuid) from public,anon,authenticated;
grant execute on function private.primary_borrower_membership(uuid) to service_role;

create or replace function public.pihub_provision_borrower_identity(caller_user_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare existing_org uuid;user_email text;metadata jsonb;requested_name text;requested_org text;new_org uuid;
begin
 if caller_user_id is null then raise exception 'caller_required' using errcode='22023';end if;
 select m.organization_id into existing_org from public.organization_members m where m.user_id=caller_user_id and m.status='active' limit 1;
 if existing_org is not null then return jsonb_build_object('provisioned',false,'organizationId',existing_org);end if;
 select u.email,coalesce(u.raw_user_meta_data,'{}'::jsonb) into user_email,metadata from auth.users u where u.id=caller_user_id;
 if user_email is null then raise exception 'authenticated_user_not_found' using errcode='42501';end if;
 requested_name:=nullif(trim(coalesce(metadata->>'display_name',metadata->>'name','')),'');requested_org:=nullif(trim(coalesce(metadata->>'organization_name','')),'');if requested_org is null then requested_org:=split_part(user_email,'@',1)||' organization';end if;
 insert into public.organizations(public_id,legal_name,verification_status) values('ORG-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)),requested_org,'pending') returning id into new_org;
 insert into public.profiles(user_id,display_name,preferred_locale) values(caller_user_id,coalesce(requested_name,split_part(user_email,'@',1)),'en') on conflict(user_id) do update set display_name=excluded.display_name,updated_at=now();
 insert into public.organization_members(organization_id,user_id,role,status,invited_at) values(new_org,caller_user_id,'owner','active',now());
 return jsonb_build_object('provisioned',true,'organizationId',new_org);
end $$;
revoke all on function public.pihub_provision_borrower_identity(uuid) from public,anon,authenticated;grant execute on function public.pihub_provision_borrower_identity(uuid) to service_role;

create or replace function public.pihub_session_context(caller_user_id uuid)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb;
begin
 select jsonb_build_object('userId',caller_user_id,'displayName',coalesce(p.display_name,''),'preferredLocale',coalesce(p.preferred_locale,'en'),'organization',case when membership.organization_id is null then null else jsonb_build_object('id',membership.organization_id,'name',membership.organization_name,'role',membership.member_role,'verificationStatus',membership.verification_status) end,'modules',(select coalesce(jsonb_agg(module_name order by module_name),'[]'::jsonb) from(select distinct module_name from(select 'borrower'::text module_name where membership.organization_id is not null union all select 'advisory' where exists(select 1 from public.platform_roles r where r.user_id=caller_user_id and r.role='advisory') union all select 'investor' where exists(select 1 from public.platform_roles r where r.user_id=caller_user_id and r.role='investor') union all select 'admin' where exists(select 1 from public.platform_roles r where r.user_id=caller_user_id and r.role in('admin','compliance','operations')))q)d)) into result from(select 1)seed left join public.profiles p on p.user_id=caller_user_id left join lateral private.primary_borrower_membership(caller_user_id) membership on true;
 return result;
end $$;
revoke all on function public.pihub_session_context(uuid) from public,anon,authenticated;grant execute on function public.pihub_session_context(uuid) to service_role;

create or replace function private.sync_snapshot_applications(target_org uuid,state jsonb,actor uuid)
returns void language plpgsql security definer set search_path='' as $$
declare item jsonb;app_id text;app_status public.pihub_application_status;
begin
 for item in select value from jsonb_array_elements(coalesce(state->'applications','[]'::jsonb)) loop
  app_id:=nullif(item->>'id','');if app_id is null then continue;end if;
  begin app_status:=(coalesce(item->>'status','draft'))::public.pihub_application_status;exception when invalid_text_representation then app_status:='draft';end;
  insert into public.applications(id,organization_id,name,status,product_id,financing,company,project,financials,section_completion,version,submitted_at,created_at,updated_at) values(app_id,target_org,coalesce(nullif(item->>'name',''),'Untitled financing request'),app_status,nullif(item#>>'{financing,productId}',''),coalesce(item->'financing','{}'::jsonb),coalesce(item->'company','{}'::jsonb),coalesce(item->'project','{}'::jsonb),coalesce(item->'financials','{}'::jsonb),coalesce(item->'sectionCompletion','{}'::jsonb),greatest(coalesce((item->>'version')::int,1),1),nullif(item->>'submittedAt','')::timestamptz,coalesce(nullif(item->>'createdAt','')::timestamptz,now()),coalesce(nullif(item->>'updatedAt','')::timestamptz,now())) on conflict(id) do update set name=excluded.name,status=excluded.status,product_id=excluded.product_id,financing=excluded.financing,company=excluded.company,project=excluded.project,financials=excluded.financials,section_completion=excluded.section_completion,version=excluded.version,submitted_at=excluded.submitted_at,updated_at=excluded.updated_at where public.applications.organization_id=target_org;
  insert into public.application_module_states(application_id,module,state,revision,updated_at) values(app_id,'borrower',case when app_status='draft' then 'in_progress' else 'completed' end,1,now()) on conflict(application_id,module) do update set state=excluded.state,updated_at=now();
  insert into public.application_module_states(application_id,module,state,revision,updated_at) values(app_id,'advisory','not_started',0,now()),(app_id,'admin','not_started',0,now()),(app_id,'investor','not_started',0,now()) on conflict(application_id,module) do nothing;
 end loop;
end $$;
revoke all on function private.sync_snapshot_applications(uuid,jsonb,uuid) from public,anon,authenticated;

create or replace function public.pihub_borrower_initialize_workspace(caller_user_id uuid,initial_snapshot jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare membership record;current_row public.borrower_workspace_states%rowtype;
begin
 select * into membership from private.primary_borrower_membership(caller_user_id);if membership.organization_id is null then raise exception 'borrower_membership_required' using errcode='42501';end if;
 select * into current_row from public.borrower_workspace_states w where w.organization_id=membership.organization_id;if current_row.organization_id is not null then return jsonb_build_object('revision',current_row.revision,'snapshot',current_row.snapshot,'initialized',false);end if;
 if initial_snapshot is null or jsonb_typeof(initial_snapshot)<>'object' then raise exception 'invalid_snapshot' using errcode='22023';end if;if initial_snapshot#>>'{organization,id}'<>membership.organization_id::text then raise exception 'snapshot_organization_mismatch' using errcode='42501';end if;
 perform private.sync_snapshot_applications(membership.organization_id,initial_snapshot,caller_user_id);insert into public.borrower_workspace_states(organization_id,snapshot,revision,updated_by) values(membership.organization_id,initial_snapshot,1,caller_user_id) returning * into current_row;return jsonb_build_object('revision',1,'snapshot',current_row.snapshot,'initialized',true);
end $$;
revoke all on function public.pihub_borrower_initialize_workspace(uuid,jsonb) from public,anon,authenticated;grant execute on function public.pihub_borrower_initialize_workspace(uuid,jsonb) to service_role;

create or replace function private.command_targets(command_name text) returns text[] language sql immutable set search_path='' as $$ select case when command_name in('application.create','application.create_from_version') then array['advisory']::text[] when command_name in('application.submit','application.withdraw','application.status.request','application.section.update','document.upload.finalize','document.remove') then array['advisory','admin']::text[] when command_name='request.respond' then array['advisory','admin','investor']::text[] when command_name in('terms.decide','closing.item.set') then array['advisory','investor']::text[] when command_name like 'servicing.%' or command_name in('reporting.submit','payment.notice.create') then array['advisory','admin','investor']::text[] when command_name in('organization.member.invite','organization.member.invitation.resend','organization.member.update','privacy.request.create') then array['admin']::text[] when command_name='borrower.feature' then array['advisory','admin']::text[] else array['advisory']::text[] end $$;
revoke all on function private.command_targets(text) from public,anon,authenticated;

create or replace function public.pihub_borrower_commit_workspace(caller_user_id uuid,command_idempotency_key text,command_name text,aggregate_key text,command_payload jsonb,expected_revision bigint,next_snapshot jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare membership record;current_row public.borrower_workspace_states%rowtype;prior record;next_revision bigint;target_modules text[];event_id uuid;app_id text;app_status text;
begin
 if nullif(trim(command_idempotency_key),'') is null then raise exception 'idempotency_key_required' using errcode='22023';end if;
 if command_name not in('application.create','application.create_from_version','application.withdraw','application.section.update','application.submit','application.status.request','document.upload.finalize','document.remove','request.respond','notification.read','notification.read_all','organization.member.invite','organization.member.invitation.resend','organization.member.update','terms.decide','closing.item.set','preference.product.saved.toggle','preference.product.compare.toggle','support.request.create','servicing.request.create','servicing.request.withdraw','reporting.submit','payment.notice.create','privacy.request.create','borrower.feature','profile.update','profile.locale.set') then raise exception 'unsupported_borrower_command' using errcode='22023';end if;
 select * into membership from private.primary_borrower_membership(caller_user_id);if membership.organization_id is null then raise exception 'borrower_membership_required' using errcode='42501';end if;
 select j.revision,j.command into prior from public.borrower_command_journal j where j.user_id=caller_user_id and j.idempotency_key=command_idempotency_key;if prior.revision is not null then select * into current_row from public.borrower_workspace_states w where w.organization_id=membership.organization_id;return jsonb_build_object('accepted',true,'idempotentReplay',true,'revision',prior.revision,'snapshot',current_row.snapshot);end if;
 select * into current_row from public.borrower_workspace_states w where w.organization_id=membership.organization_id for update;if current_row.organization_id is null then raise exception 'borrower_workspace_not_initialized' using errcode='22023';end if;if expected_revision is null or expected_revision<>current_row.revision then raise exception 'workspace_revision_conflict' using errcode='40001';end if;if next_snapshot is null or jsonb_typeof(next_snapshot)<>'object' or next_snapshot#>>'{organization,id}'<>membership.organization_id::text then raise exception 'invalid_next_snapshot' using errcode='42501';end if;
 if command_name like 'organization.member.%' and membership.member_role<>'owner' then raise exception 'owner_role_required' using errcode='42501';end if;if command_name in('application.submit','closing.item.set') and membership.member_role not in('owner','signatory') then raise exception 'signatory_role_required' using errcode='42501';end if;if command_name in('payment.notice.create','reporting.submit') and membership.member_role not in('owner','finance') then raise exception 'finance_role_required' using errcode='42501';end if;
 app_id:=coalesce(nullif(aggregate_key,''),nullif(next_snapshot->>'activeApplicationId',''));
 if command_name='application.submit' then if app_id is null then raise exception 'application_required' using errcode='22023';end if;if exists(select 1 from(values('finance'),('legal'),('signatory'))g(t) where not exists(select 1 from public.application_approvals a where a.application_id=app_id and a.approval_type=g.t and a.status='approved')) then raise exception 'submission_approvals_required' using errcode='42501';end if;select value->>'status' into app_status from jsonb_array_elements(coalesce(next_snapshot->'applications','[]'::jsonb)) where value->>'id'=app_id limit 1;if app_status<>'submitted' then raise exception 'submitted_snapshot_required' using errcode='22023';end if;end if;
 if command_name='notification.read_all' then update public.notifications set read_at=coalesce(read_at,now()) where user_id=caller_user_id;elsif command_name='notification.read' then update public.notifications set read_at=coalesce(read_at,now()) where user_id=caller_user_id and id=(command_payload->>'notificationId')::uuid;end if;
 next_revision:=current_row.revision+1;perform private.sync_snapshot_applications(membership.organization_id,next_snapshot,caller_user_id);update public.borrower_workspace_states set snapshot=next_snapshot,revision=next_revision,updated_by=caller_user_id,updated_at=now() where organization_id=membership.organization_id;
 insert into public.borrower_command_journal(organization_id,application_id,user_id,idempotency_key,command,aggregate_id,payload,revision) values(membership.organization_id,case when app_id in(select a.id from public.applications a where a.organization_id=membership.organization_id) then app_id else null end,caller_user_id,command_idempotency_key,command_name,aggregate_key,coalesce(command_payload,'{}'::jsonb),next_revision);
 if command_name not in('notification.read','notification.read_all','preference.product.saved.toggle','preference.product.compare.toggle','profile.update','profile.locale.set') then target_modules:=private.command_targets(command_name);insert into public.outbox_events(event_key,aggregate_type,aggregate_id,event_type,target_modules,payload,created_by,organization_id,application_id,schema_version) values('command:'||command_idempotency_key,'application',coalesce(app_id,membership.organization_id::text),'borrower.'||replace(command_name,'.','_'),target_modules,jsonb_build_object('command',command_name,'aggregateId',aggregate_key,'revision',next_revision),caller_user_id,membership.organization_id,case when app_id in(select a.id from public.applications a where a.organization_id=membership.organization_id) then app_id else null end,1) returning id into event_id;end if;
 if command_name='application.submit' then update public.application_module_states set state='completed',updated_at=now() where application_id=app_id and module='borrower';insert into public.workflow_handoffs(handoff_key,organization_id,application_id,from_module,to_module,handoff_type,status,source_event_id,created_by,updated_at) values('submission:'||app_id||':advisory',membership.organization_id,app_id,'borrower','advisory','application_submission','pending',event_id,caller_user_id,now()) on conflict(handoff_key) do update set source_event_id=excluded.source_event_id,updated_at=now();end if;
 return jsonb_build_object('accepted',true,'revision',next_revision,'snapshot',next_snapshot,'eventId',event_id);
end $$;
revoke all on function public.pihub_borrower_commit_workspace(uuid,text,text,text,jsonb,bigint,jsonb) from public,anon,authenticated;grant execute on function public.pihub_borrower_commit_workspace(uuid,text,text,text,jsonb,bigint,jsonb) to service_role;

create table if not exists public.document_upload_intents(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,application_id text not null references public.applications(id) on delete cascade,document_id text not null,version_id uuid not null unique default gen_random_uuid(),replace_document_id text references public.documents(id) on delete restrict,object_path text not null unique,original_name text not null,mime_type text not null,size_bytes bigint not null check(size_bytes>=0 and size_bytes<=26214400),category text not null,created_by uuid not null references auth.users(id) on delete cascade,expires_at timestamptz not null default(now()+interval '15 minutes'),consumed_at timestamptz,created_at timestamptz not null default now());
create index if not exists document_upload_intents_owner_idx on public.document_upload_intents(created_by,expires_at desc);create index if not exists document_upload_intents_application_idx on public.document_upload_intents(application_id,created_at desc);alter table public.document_upload_intents enable row level security;revoke all on public.document_upload_intents from public,anon,authenticated;grant all on public.document_upload_intents to service_role;
create or replace function public.pihub_create_document_upload_intent(caller_user_id uuid,application_key text,original_file_name text,content_type text,content_size bigint,document_category text,replace_document_key text default null) returns jsonb language plpgsql security definer set search_path='' as $$ declare target_org uuid;intent_id uuid;version_key uuid;document_key text;safe_name text;path text;begin select a.organization_id into target_org from public.applications a join public.organization_members m on m.organization_id=a.organization_id where a.id=application_key and m.user_id=caller_user_id and m.status='active' limit 1;if target_org is null then raise exception 'application_access_forbidden' using errcode='42501';end if;if content_size<0 or content_size>26214400 then raise exception 'document_size_not_allowed' using errcode='22023';end if;if content_type not in('application/pdf','image/png','image/jpeg','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.wordprocessingml.document') then raise exception 'document_type_not_allowed' using errcode='22023';end if;intent_id:=gen_random_uuid();version_key:=gen_random_uuid();document_key:=coalesce(replace_document_key,'DOC-'||upper(substr(replace(version_key::text,'-',''),1,16)));safe_name:=regexp_replace(coalesce(nullif(original_file_name,''),'document'),'[^A-Za-z0-9._-]+','_','g');path:=target_org::text||'/'||application_key||'/'||document_key||'/'||version_key::text||'/'||safe_name;insert into public.document_upload_intents(id,organization_id,application_id,document_id,version_id,replace_document_id,object_path,original_name,mime_type,size_bytes,category,created_by) values(intent_id,target_org,application_key,document_key,version_key,replace_document_key,path,original_file_name,content_type,content_size,document_category,caller_user_id);return jsonb_build_object('intentId',intent_id,'documentId',document_key,'versionId',version_key,'objectPath',path,'expiresAt',now()+interval '15 minutes');end $$;
revoke all on function public.pihub_create_document_upload_intent(uuid,text,text,text,bigint,text,text) from public,anon,authenticated;grant execute on function public.pihub_create_document_upload_intent(uuid,text,text,text,bigint,text,text) to service_role;

alter table public.notifications add column if not exists source_event_id uuid references public.outbox_events(id) on delete set null;
create unique index if not exists notifications_user_source_event_unique on public.notifications(user_id,source_event_id) where source_event_id is not null;
create or replace function private.notify_borrower_domain_event() returns trigger language plpgsql security definer set search_path='' as $$ declare title_text text;body_text text;href_text text;begin if not('borrower'=any(new.target_modules)) then return new;end if;if new.event_type like '%request%' then title_text:='PiHub request updated';body_text:='A PiHub request or response needs your attention.';href_text:='/requests';elsif new.event_type like '%compliance%' or new.event_type like '%kyb%' or new.event_type like '%kyc%' then title_text:='Compliance readiness updated';body_text:='Your borrower-facing verification status or required actions changed.';href_text:='/company';elsif new.event_type like '%document%' then title_text:='Document workflow updated';body_text:='A document or document review changed in PiHub.';href_text:='/documents';elsif new.event_type like '%term%' or new.event_type like '%investor%' or new.event_type like '%decision%' then title_text:='Financing decision updated';body_text:='Terms, investor review or a financing decision changed.';href_text:='/closing';elsif new.event_type like '%facility%' or new.event_type like '%payment%' or new.event_type like '%covenant%' or new.event_type like '%reporting%' or new.event_type like '%servicing%' then title_text:='Servicing update';body_text:='A post-funding obligation or servicing record changed.';href_text:='/servicing';else title_text:='PiHub workflow updated';body_text:='Your financing workflow changed in another PiHub module.';href_text:='/';end if;insert into public.notifications(user_id,kind,title,body,href,source_event_id,created_at) select m.user_id,'workflow',title_text,body_text,href_text,new.id,now() from public.organization_members m where m.organization_id=new.organization_id and m.status='active' on conflict(user_id,source_event_id) where source_event_id is not null do nothing;return new;end $$;
revoke all on function private.notify_borrower_domain_event() from public,anon,authenticated;drop trigger if exists outbox_borrower_notification on public.outbox_events;create trigger outbox_borrower_notification after insert on public.outbox_events for each row execute function private.notify_borrower_domain_event();
create or replace function private.bump_workspace_for_notification() returns trigger language plpgsql security definer set search_path='' as $$ declare target_org uuid;begin select m.organization_id into target_org from public.organization_members m where m.user_id=new.user_id and m.status='active' order by case m.role::text when 'owner' then 0 else 1 end limit 1;if target_org is not null then update public.borrower_workspace_states set revision=revision+1,updated_at=now() where organization_id=target_org;end if;return new;end $$;
revoke all on function private.bump_workspace_for_notification() from public,anon,authenticated;drop trigger if exists notifications_workspace_revision on public.notifications;create trigger notifications_workspace_revision after insert on public.notifications for each row execute function private.bump_workspace_for_notification();

create table if not exists public.data_connection_authorization_intents(id uuid primary key default gen_random_uuid(),state_token uuid not null unique default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,provider text not null check(provider in('datev','finapi','erp_api')),scopes text[] not null default '{}',return_to text not null,expires_at timestamptz not null default(now()+interval '10 minutes'),used_at timestamptz,created_at timestamptz not null default now());
create index if not exists data_connection_auth_intents_user_idx on public.data_connection_authorization_intents(user_id,expires_at desc);alter table public.data_connection_authorization_intents enable row level security;revoke all on public.data_connection_authorization_intents from public,anon,authenticated;grant all on public.data_connection_authorization_intents to service_role;
create or replace function public.pihub_create_data_connection_authorization_intent(caller_user_id uuid,provider_name text,requested_scopes text[],return_location text) returns jsonb language plpgsql security definer set search_path='' as $$ declare membership record;intent public.data_connection_authorization_intents%rowtype;begin if provider_name not in('datev','finapi','erp_api') then raise exception 'provider_not_supported' using errcode='22023';end if;select * into membership from private.primary_borrower_membership(caller_user_id);if membership.organization_id is null then raise exception 'borrower_membership_required' using errcode='42501';end if;if nullif(trim(return_location),'') is null or left(return_location,1)<>'/' then raise exception 'invalid_return_location' using errcode='22023';end if;insert into public.data_connection_authorization_intents(organization_id,user_id,provider,scopes,return_to) values(membership.organization_id,caller_user_id,provider_name,coalesce(requested_scopes,'{}'),return_location) returning * into intent;return jsonb_build_object('intentId',intent.id,'state',intent.state_token,'provider',intent.provider,'expiresAt',intent.expires_at,'returnTo',intent.return_to);end $$;
revoke all on function public.pihub_create_data_connection_authorization_intent(uuid,text,text[],text) from public,anon,authenticated;grant execute on function public.pihub_create_data_connection_authorization_intent(uuid,text,text[],text) to service_role;
create or replace function public.pihub_finalize_data_connection_authorization(caller_user_id uuid,state_value uuid,provider_connection text,token_payload jsonb,expires_value timestamptz default null,account_total int default null) returns jsonb language plpgsql security definer set search_path='' as $$ declare intent public.data_connection_authorization_intents%rowtype;secret_id uuid;connection_id text;begin select * into intent from public.data_connection_authorization_intents i where i.state_token=state_value and i.user_id=caller_user_id for update;if intent.id is null then raise exception 'authorization_intent_not_found' using errcode='42501';end if;if intent.used_at is not null then raise exception 'authorization_intent_used' using errcode='22023';end if;if intent.expires_at<=now() then raise exception 'authorization_intent_expired' using errcode='22023';end if;if token_payload is null or jsonb_typeof(token_payload)<>'object' then raise exception 'provider_token_missing' using errcode='22023';end if;secret_id:=vault.create_secret(token_payload::text,'pihub-data-connection-'||intent.id::text,'PiHub encrypted provider token payload');connection_id:='CONN-'||upper(substr(replace(intent.id::text,'-',''),1,16));insert into public.data_connections(id,organization_id,user_id,provider,label,status,scopes,provider_connection_ref,token_secret_ref,last_sync_at,expires_at,account_count) values(connection_id,intent.organization_id,caller_user_id,intent.provider,upper(intent.provider)||' connection','connected',intent.scopes,provider_connection,secret_id::text,now(),expires_value,account_total) on conflict(id) do update set status='connected',provider_connection_ref=excluded.provider_connection_ref,token_secret_ref=excluded.token_secret_ref,last_sync_at=now(),expires_at=excluded.expires_at,account_count=excluded.account_count,error=null,updated_at=now();update public.data_connection_authorization_intents set used_at=now() where id=intent.id;return jsonb_build_object('connectionId',connection_id,'provider',intent.provider,'status','connected','returnTo',intent.return_to);end $$;
revoke all on function public.pihub_finalize_data_connection_authorization(uuid,uuid,text,jsonb,timestamptz,int) from public,anon,authenticated;grant execute on function public.pihub_finalize_data_connection_authorization(uuid,uuid,text,jsonb,timestamptz,int) to service_role;

do $$ begin if exists(select 1 from information_schema.columns where table_schema='public' and table_name='signature_envelopes' and column_name='external_envelope_ref') then alter table public.signature_envelopes rename column external_envelope_ref to external_envelope_id;end if;end $$;

create or replace function public.pihub_borrower_session_bootstrap(caller_user_id uuid,since_revision bigint default null) returns jsonb language plpgsql stable security definer set search_path='' as $$ begin return jsonb_build_object('session',public.pihub_session_context(caller_user_id),'workspace',public.pihub_borrower_workspace(caller_user_id,since_revision));end $$;
revoke all on function public.pihub_borrower_session_bootstrap(uuid,bigint) from public,anon,authenticated;grant execute on function public.pihub_borrower_session_bootstrap(uuid,bigint) to service_role;
