-- Final Borrower runtime: bounded revision patches plus safe automatic cross-module consequences.
alter table public.borrower_command_journal add column if not exists delta jsonb not null default '{}'::jsonb;

create or replace function private.top_level_json_delta(previous_state jsonb,next_state jsonb)
returns jsonb language sql immutable set search_path='' as $$
 with keys as (select jsonb_object_keys(coalesce(previous_state,'{}'::jsonb)) key union select jsonb_object_keys(coalesce(next_state,'{}'::jsonb)) key)
 select coalesce(jsonb_object_agg(key,next_state->key),'{}'::jsonb) from keys where (previous_state->key) is distinct from (next_state->key)
$$;
revoke all on function private.top_level_json_delta(jsonb,jsonb) from public,anon,authenticated;grant execute on function private.top_level_json_delta(jsonb,jsonb) to service_role;

create or replace function public.pihub_borrower_workspace(caller_user_id uuid,since_revision bigint default null)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare membership record;row_state public.borrower_workspace_states%rowtype;delta_count int;projected_snapshot jsonb;merged_patch jsonb:='{}'::jsonb;change_row record;
begin
 select * into membership from private.primary_borrower_membership(caller_user_id);if membership.organization_id is null then raise exception 'borrower_membership_required' using errcode='42501';end if;
 select * into row_state from public.borrower_workspace_states w where w.organization_id=membership.organization_id;if row_state.organization_id is null then return jsonb_build_object('initialized',false,'revision',0);end if;
 projected_snapshot:=jsonb_set(row_state.snapshot,'{notifications}',coalesce((select jsonb_agg(jsonb_build_object('id',n.id::text,'kind',n.kind,'title',n.title,'body',n.body,'href',n.href,'read',n.read_at is not null,'createdAt',n.created_at) order by n.created_at desc) from public.notifications n where n.user_id=caller_user_id),'[]'::jsonb),true);
 if since_revision is not null and since_revision=row_state.revision then return jsonb_build_object('initialized',true,'unchanged',true,'revision',row_state.revision);end if;
 if since_revision is not null and since_revision>=0 and since_revision<row_state.revision then select count(*)::int into delta_count from public.borrower_command_journal j where j.organization_id=membership.organization_id and j.revision>since_revision;if delta_count between 1 and 50 and delta_count=(row_state.revision-since_revision) and not exists(select 1 from public.borrower_command_journal j where j.organization_id=membership.organization_id and j.revision>since_revision and(j.delta is null or jsonb_typeof(j.delta)<>'object')) then for change_row in select j.delta from public.borrower_command_journal j where j.organization_id=membership.organization_id and j.revision>since_revision order by j.revision loop merged_patch:=merged_patch||change_row.delta;end loop;return jsonb_build_object('initialized',true,'revision',row_state.revision,'patch',merged_patch);end if;end if;
 return jsonb_build_object('initialized',true,'revision',row_state.revision,'snapshot',projected_snapshot);
end $$;
revoke all on function public.pihub_borrower_workspace(uuid,bigint) from public,anon,authenticated;grant execute on function public.pihub_borrower_workspace(uuid,bigint) to service_role;

create or replace function public.pihub_borrower_commit_workspace_v2(caller_user_id uuid,command_idempotency_key text,command_name text,aggregate_key text,command_payload jsonb,expected_revision bigint,previous_snapshot jsonb,next_snapshot jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare membership record;current_row public.borrower_workspace_states%rowtype;intent public.document_upload_intents%rowtype;result jsonb;corrected jsonb;final_snapshot jsonb;next_version int;prior_revision bigint;
begin
 select j.revision into prior_revision from public.borrower_command_journal j where j.user_id=caller_user_id and j.idempotency_key=command_idempotency_key;if prior_revision is not null then result:=public.pihub_borrower_workspace(caller_user_id,null);return jsonb_build_object('accepted',true,'idempotentReplay',true,'revision',result->'revision','snapshot',result->'snapshot');end if;
 select * into membership from private.primary_borrower_membership(caller_user_id);if membership.organization_id is null then raise exception 'borrower_membership_required' using errcode='42501';end if;select * into current_row from public.borrower_workspace_states w where w.organization_id=membership.organization_id for update;if current_row.organization_id is null then raise exception 'borrower_workspace_not_initialized' using errcode='22023';end if;if expected_revision is null or expected_revision<>current_row.revision then raise exception 'workspace_revision_conflict' using errcode='40001';end if;if previous_snapshot is null or current_row.snapshot<>previous_snapshot then raise exception 'workspace_snapshot_conflict' using errcode='40001';end if;
 if command_name='document.upload.finalize' then select * into intent from public.document_upload_intents i where i.version_id=(command_payload->>'versionId')::uuid and i.organization_id=membership.organization_id and i.created_by=caller_user_id for update;if intent.id is null then raise exception 'document_upload_intent_not_found' using errcode='22023';end if;if intent.consumed_at is not null then raise exception 'document_upload_intent_consumed' using errcode='22023';end if;if intent.expires_at<=now() then raise exception 'document_upload_intent_expired' using errcode='22023';end if;if aggregate_key is distinct from intent.document_id then raise exception 'document_upload_intent_mismatch' using errcode='42501';end if;if command_payload->>'applicationId' is distinct from intent.application_id then raise exception 'document_application_mismatch' using errcode='42501';end if;end if;
 result:=public.pihub_borrower_commit_workspace(caller_user_id,command_idempotency_key,command_name,aggregate_key,command_payload,expected_revision,next_snapshot);
 if command_name='document.upload.finalize' then select coalesce(max(v.version),0)+1 into next_version from public.document_versions v where v.document_id=intent.document_id;insert into public.documents(id,application_id,category,required,status,current_version,created_at,updated_at) values(intent.document_id,intent.application_id,intent.category,false,'submitted',next_version,now(),now()) on conflict(id) do update set category=excluded.category,status='submitted',current_version=excluded.current_version,updated_at=now();insert into public.document_versions(id,document_id,version,object_path,original_name,mime_type,size_bytes,malware_status,uploaded_by,uploaded_at) values(intent.version_id,intent.document_id,next_version,intent.object_path,intent.original_name,intent.mime_type,intent.size_bytes,'pending',caller_user_id,now());update public.document_upload_intents set consumed_at=now() where id=intent.id;corrected:=next_snapshot||jsonb_build_object('documents',(select coalesce(jsonb_agg(case when d->>'blobKey'=intent.version_id::text then d||jsonb_build_object('id',intent.document_id,'applicationId',intent.application_id,'name',intent.original_name,'mimeType',intent.mime_type,'size',intent.size_bytes,'category',intent.category,'version',next_version,'status','submitted') else d end order by ord),'[]'::jsonb) from jsonb_array_elements(coalesce(next_snapshot->'documents','[]'::jsonb)) with ordinality x(d,ord)));update public.borrower_workspace_states set snapshot=corrected,updated_at=now() where organization_id=membership.organization_id;result:=jsonb_set(result,'{snapshot}',corrected,true);end if;
 final_snapshot:=coalesce(result->'snapshot',next_snapshot);update public.borrower_command_journal set delta=private.top_level_json_delta(previous_snapshot,final_snapshot) where user_id=caller_user_id and idempotency_key=command_idempotency_key;return result;
end $$;
revoke all on function public.pihub_borrower_commit_workspace_v2(uuid,text,text,text,jsonb,bigint,jsonb,jsonb) from public,anon,authenticated;grant execute on function public.pihub_borrower_commit_workspace_v2(uuid,text,text,text,jsonb,bigint,jsonb,jsonb) to service_role;

create or replace function private.emit_safe_cross_module_consequence() returns trigger language plpgsql security definer set search_path='' as $$
declare app_id text;org_id uuid;event_type text;targets text[];safe_payload jsonb:='{}'::jsonb;actor uuid;
begin if tg_table_name='application_module_states' then app_id:=new.application_id;event_type:='workflow.'||new.module||'.state_updated';targets:=array_remove(array['borrower','advisory','admin','investor']::text[],new.module);safe_payload:=jsonb_build_object('module',new.module,'state',new.state,'revision',new.revision);actor:=new.owner_user_id;elsif tg_table_name='due_diligence_workstreams' then app_id:=new.application_id;event_type:='advisory.due_diligence.updated';targets:=array['borrower','admin']::text[];safe_payload:=jsonb_build_object('workstreamKey',new.workstream_key,'title',new.title,'status',new.status,'dueAt',new.due_at);actor:=new.owner_user_id;elsif tg_table_name='compliance_cases' then app_id:=new.application_id;org_id:=new.organization_id;event_type:='admin.compliance.updated';targets:=array['borrower','advisory']::text[];safe_payload:=jsonb_build_object('caseType',new.case_type,'status',new.status,'outcome',new.outcome);actor:=new.owner_user_id;elsif tg_table_name='deal_publications' then app_id:=new.application_id;event_type:='advisory.publication.updated';targets:=array['borrower','investor','admin']::text[];safe_payload:=jsonb_build_object('status',new.status,'title',new.title,'version',new.version,'publishedAt',new.published_at);actor:=coalesce(new.published_by,new.approved_by);elsif tg_table_name='investor_commitments' then app_id:=new.application_id;event_type:='investor.commitment.updated';targets:=array['borrower','advisory','admin']::text[];safe_payload:=jsonb_build_object('status',new.status,'currency',new.currency);actor:=new.investor_user_id;elsif tg_table_name='investor_decisions' then select c.application_id into app_id from public.investor_commitments c where c.id=new.commitment_id;event_type:='investor.decision.updated';targets:=array['borrower','advisory','admin']::text[];safe_payload:=jsonb_build_object('decisionStage',new.decision_stage,'outcome',new.outcome,'decidedAt',new.decided_at);actor:=new.decided_by;else return new;end if;if org_id is null and app_id is not null then select a.organization_id into org_id from public.applications a where a.id=app_id;end if;if org_id is null then return new;end if;insert into public.outbox_events(event_key,aggregate_type,aggregate_id,event_type,target_modules,payload,created_by,organization_id,application_id,schema_version) values('domain:'||tg_table_name||':'||coalesce(app_id,org_id::text)||':'||gen_random_uuid()::text,case when app_id is null then 'organization' else 'application' end,coalesce(app_id,org_id::text),event_type,targets,safe_payload,actor,org_id,app_id,1);return new;end $$;
revoke all on function private.emit_safe_cross_module_consequence() from public,anon,authenticated;
drop trigger if exists application_module_state_consequence on public.application_module_states;create trigger application_module_state_consequence after insert or update of state,revision on public.application_module_states for each row execute function private.emit_safe_cross_module_consequence();
drop trigger if exists due_diligence_consequence on public.due_diligence_workstreams;create trigger due_diligence_consequence after insert or update of status,due_at on public.due_diligence_workstreams for each row execute function private.emit_safe_cross_module_consequence();
drop trigger if exists compliance_case_consequence on public.compliance_cases;create trigger compliance_case_consequence after insert or update of status,outcome on public.compliance_cases for each row execute function private.emit_safe_cross_module_consequence();
drop trigger if exists deal_publication_consequence on public.deal_publications;create trigger deal_publication_consequence after insert or update of status,published_at on public.deal_publications for each row execute function private.emit_safe_cross_module_consequence();
drop trigger if exists investor_commitment_consequence on public.investor_commitments;create trigger investor_commitment_consequence after insert or update of status on public.investor_commitments for each row execute function private.emit_safe_cross_module_consequence();
drop trigger if exists investor_decision_consequence on public.investor_decisions;create trigger investor_decision_consequence after insert or update of outcome,decision_stage on public.investor_decisions for each row execute function private.emit_safe_cross_module_consequence();
